services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      RUST_LOG: "debug"
      RUST_BACKTRACE: 1
    volumes:
      - ./storage:/usr/src/noadick/storage
